In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
wrd_to_idx = {"i" : 0, "love" : 1, "eating" : 2, "and" : 3, "sleeping" : 4}
embeddings = nn.Embedding(5,7) #Embedding(<no. of words you have>, <each word will be represented by this much values in a vector>)

word_index = torch.tensor([wrd_to_idx["love"]])
print(word_index)

tensor([1])


In [3]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[ 0.5289, -0.8516, -1.7209,  0.8894,  2.5584,  0.2902,  0.4849]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [4]:
all_indices = torch.tensor([w for w in range(5)], dtype = torch.long)
all_words = embeddings(all_indices)
print(all_words)
print(all_words.shape)

tensor([[-1.5391, -0.3768,  0.7678, -0.1656,  0.6925,  1.4744, -0.4070],
        [ 0.5289, -0.8516, -1.7209,  0.8894,  2.5584,  0.2902,  0.4849],
        [-1.5057,  0.0075, -0.3196,  1.2161,  2.3828,  0.0497,  0.2652],
        [-0.4407,  1.0340,  0.3523,  0.2906, -0.6866,  0.2268,  0.9042],
        [-0.9004, -1.2619, -0.5149, -0.8546,  1.3304,  0.4886,  0.2645]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])
